### ISSUE TITLE
Implement JSON-RPC client for peach-stats

### ISSUE THREAD

**Issue by mycognosist** [peachcloud/peach-probe#1]
Implement a JSON-RPC client to probe the `peach-stats` microservice and report if any responses do not meet expectations.

As per the [JSON-RPC spec](https://www.jsonrpc.org/specification), the microservice must reply with either a result or an error. Initial work on `peach-probe` can focus purely on the response type, ie. for each method exposed by the `peach-stats` RPC API, what is the response? Result or error?

Once the basic binary testing is in place, extend the functionality of `peach-probe` to report the code and message in the case of an error. This gives the user of `peach-probe` an insight into what is not working and why that might be the case.

**Comment by mycognosist** [comment]
The public API of `peach-stats` is available in the [README](https://github.com/peachcloud/peach-stats#json-rpc-api).

`peach-web` already has an implementation of a [JSON-RPC client for `peach-stats`](https://github.com/peachcloud/peach-web/blob/master/src/stats_client.rs), which may be very helpful as a reference.

The `peach-stats` client code is called in [`device.rs`](https://github.com/peachcloud/peach-web/blob/master/src/context.rs) of `peach-web`, where it is used to build a context object for the templating engine. This should give an insight into how the client code methods are called and handled.

**Comment by mhfowler** [comment]
@mycognosist I wonder if it would make sense to create an additional github repo called peach-lib or peach-api or something like this, and put the code for the clients of the microservices there, and have peach-web and peach-probe both use peach-lib, so stats_client and oled_client are not duplicated between peach-probe and peach-web 

otherwise, I'm imagining I would pretty much copy this code exactly for peach-probe https://github.com/peachcloud/peach-web/blob/2c54652b66e148131e44f0b53c7d5e6166bbec72/src/stats_client.rs#L73

alternatively peach-probe could perhaps be a part of peach-web, or we can also just have duplicate code

**Comment by mycognosist** [comment]
@mhfowler 

Excellent idea. Let's move the JSON-RPC client code into a separate repo (`peach-lib`) and import that where needed (currently `peach-web`, `peach-menu` and `peach-probe`). I can work on that.

**Comment by mycognosist** [comment]
@mhfowler 

I've created the [peach-lib](https://github.com/peachcloud/peach-lib) library to house the JSON-RPC client code. It can be imported as a dependency (in `Cargo.toml` as follows):

`peach-lib = { git = "https://github.com/peachcloud/peach-lib", branch = "main" }`

Example usage:

`use peach_lib::network_client;`

`network_client::activate_ap()?;`

**Comment by mhfowler** [comment]
Implemented by https://github.com/peachcloud/peach-probe/pull/6
